### ISSUE TITLE
cocos creator 3.8.1  找不到模块

### ISSUE THREAD

**Issue by axiullo** [k8w/tsrpc-examples#10]
![图片](https://github.com/k8w/tsrpc-examples/assets/6184234/9b9e5ccd-08a7-4862-97e8-16a46eae63cd)
新建个项目，服务器同步过来文件后，cocos报错找不到模块。 但是例子项目没有报错。
对比配置文件没有找到差别。 是哪里配置有问题么？

**Comment by axiullo** [comment]
我把creator 的安装路径从c盘移到了其他盘，好像就不报错了。

**Comment by wpftencent** [comment]
@k8w mac + 3.8.2也出现这个问题了。

<img width="629" alt="Image" src="https://github.com/user-attachments/assets/f0ba4c3c-1d87-4a94-a2d7-25f716c3888a" />
