### ISSUE TITLE
运行 npm run doc 无文件生成

### ISSUE THREAD

**Issue by lzy2014love** [k8w/tsrpc-examples#4]

**Comment by k8w** [comment]
有什么具体报错吗？
检查一下 `tsrpc.config.ts` 中 `proto` 内的 `docDir` 有无配置？

**Comment by k8w** [comment]
方便的话可以提供一下 Demo

**Comment by lzy2014love** [comment]
原因找到了， 只有部分例子的后端项目 tsrpc.config.ts 中 proto 内的 docDir 有配置， 没有配置的话运行 npm run doc 没有报错和日志提示直接结束了
